[package]
name = "heart-stats-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
egui_plot = "0.27.2"
env_logger = "0.11.3"
locales = "0.1.0"
log = "0.4.21"
